# Generated by Django 3.1.7 on 2021-05-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20210501_1420'),
        ('mainApp', '0003_doctor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
