# Generated by Django 3.1.7 on 2021-05-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210501_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
